# TODO: This isn't working anymore since I moved to a single repository for all Exercism tracks
name: Continuous integration

# Running on the branch main and on all PRs
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  continuous_integration:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Elixir and OTP
        uses: erlef/setup-beam@v1.15
        id: setup-beam
        with:
          otp-version: '25'
          elixir-version: '1.14.2'

      - name: Check format of Elixir code # https://hexdocs.pm/mix/main/Mix.Tasks.Format.html
        run: mix format --dry-run --check-formatted

      - name: Ensure the Elixir code compiles # https://hexdocs.pm/mix/Mix.Tasks.Compile.html
        run: mix compile --all-warnings --warning-as-errors

      - name: Run tests # https://hexdocs.pm/mix/Mix.Tasks.Test.html
        run: mix test
